### ISSUE TITLE
Improving Patch application

### ISSUE THREAD

**Issue by mettke** [itmettkeDE/cargo-patch#3]
Currently the apply patch operation is very rudimentary, working with line numbers only. It should, however, be checked whether we are actually replacing the correct lines which might even be a few lines higher or lower. Also we may want to check whether the lines we replace actually are the same to the lines in the patch file.

**Comment by jirutka** [comment]
Why you don’t simply call `patch` command?

**Comment by mettke** [comment]
Well its difficult. The patch command may be available on a system but it also may not. I'm not sure whether I want to make it a hard dependency. Also I'm not sure whether it is available in Windows or MacOS which would make it more difficult for them to use this application 🤔
