### ISSUE TITLE
Expose as lib?

### ISSUE THREAD

**Issue by sonewman** [itmettkeDE/cargo-patch#51]
I don't know how you feel about this, but i was wondering what your thoughts would be on exposing this as a lib so it could be used in a `build.rs`?

Doing this would simplify adding it as a dependency and patching automatically as it could be included as a dependency rather than requiring a separate install and then triggered during a build

**Comment by mettke** [comment]
That is a very interesting idea. How would that like like? 

Like a single function which would perform the same operation as the binary?

```
cargo_patch::perform_patch()
```

**Comment by mettke** [comment]
This should work with Version 0.3.2. If it doesn't then feel free to create a new issue.
